#!/usr/bin/python3
'''factorizing set of given numbers in a file to produce two small numbers'''
from sys import argv


def factorize(number_to_check):
    '''finding two small numbers that multiply to give a given number'''
    n = 2

    if number_to_check < 2:
        return
    
    while number_to_check % n:
        n += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number_to_check, number_to_check / n, n))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number_to_check = int(line.split('\n')[0])
            factorize(number_to_check)
            line = file.readline()
except:
    pass
